2022-01-21 18:15:22,526 ERROR    client.py Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2022-01-21 18:15:53,517 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 18:15:53,518 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 18:26:11,335 ERROR    client.py Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2022-01-21 18:26:11,335 ERROR    client.py Не удалось отправить сообщение на сервер!
2022-01-21 18:54:45,553 ERROR    client.py Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2022-01-21 18:54:45,553 ERROR    client.py Не удалось отправить сообщение на сервер!
2022-01-21 18:54:45,553 ERROR    client.py Запрос на отправку или получение данных  (when sending on a datagram socket using a sendto call) no address was supplied
2022-01-21 18:54:46,555 ERROR    client.py Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2022-01-21 18:54:46,555 ERROR    client.py Не удалось отправить сообщение на сервер!
2022-01-21 18:54:46,555 ERROR    client.py Запрос на отправку или получение данных  (when sending on a datagram socket using a sendto call) no address was supplied
2022-01-21 18:55:24,431 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 18:55:24,431 DEBUG    client.py Отправлено сообщение на сервер: {"action": "error", "time": 1642780524.420497, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 18:55:24,432 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 18:55:24,432 DEBUG    client.py Отправлено сообщение на сервер: {"action": "presence", "time": 1642780524.420497, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 18:55:55,062 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 18:55:55,062 DEBUG    client.py Отправлено сообщение на сервер: {"action": "error", "time": 1642780555.051121, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 18:55:55,063 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 18:55:55,063 DEBUG    client.py Отправлено сообщение на сервер: {"action": "presence", "time": 1642780555.050118, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 18:56:34,198 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 18:56:34,198 DEBUG    client.py Отправлено сообщение на сервер: {"action": "error", "time": 1642780594.182759, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 18:56:34,199 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 18:56:34,199 DEBUG    client.py Отправлено сообщение на сервер: {"action": "presence", "time": 1642780594.182759, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 18:58:22,293 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 18:58:22,294 DEBUG    client.py Отправлено сообщение на сервер: {"action": "error", "time": 1642780702.282305, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 18:58:22,294 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 18:58:22,294 DEBUG    client.py Отправлено сообщение на сервер: {"action": "presence", "time": 1642780702.282305, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 18:58:22,295 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 18:58:22,295 ERROR    client.py Не удалось отправить сообщение на сервер!
2022-01-21 18:58:50,618 ERROR    client.py Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2022-01-21 19:10:36,464 ERROR    client.py Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2022-01-21 19:11:07,041 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 19:11:07,041 DEBUG    client.py Отправлено сообщение на сервер: {"action": "error", "time": 1642781467.031333, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 19:11:07,041 ERROR    client.py Не удалось отправить сообщение на сервер!
2022-01-21 19:11:07,042 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 19:11:07,042 DEBUG    client.py Отправлено сообщение на сервер: {"action": "presence", "time": 1642781467.030332, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 19:11:07,042 ERROR    client.py Не удалось отправить сообщение на сервер!
2022-01-21 19:11:07,042 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 19:13:08,175 ERROR    client.py Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2022-01-21 19:13:08,175 ERROR    client.py Не удалось отправить сообщение на сервер!
2022-01-21 19:13:08,175 ERROR    client.py Запрос на отправку или получение данных  (when sending on a datagram socket using a sendto call) no address was supplied
2022-01-21 19:13:09,177 ERROR    client.py Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2022-01-21 19:13:09,177 ERROR    client.py Не удалось отправить сообщение на сервер!
2022-01-21 19:13:09,177 ERROR    client.py Запрос на отправку или получение данных  (when sending on a datagram socket using a sendto call) no address was supplied
2022-01-21 19:13:10,188 ERROR    client.py Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2022-01-21 19:13:10,188 ERROR    client.py Не удалось отправить сообщение на сервер!
2022-01-21 19:13:10,188 ERROR    client.py Запрос на отправку или получение данных  (when sending on a datagram socket using a sendto call) no address was supplied
2022-01-21 19:13:30,229 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 19:13:30,229 DEBUG    client.py Отправлено сообщение на сервер: {"action": "error", "time": 1642781610.219136, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 19:13:30,230 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 19:13:30,230 DEBUG    client.py Отправлено сообщение на сервер: {"action": "presence", "time": 1642781610.219136, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 19:13:30,230 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 19:13:30,230 ERROR    client.py Не удалось отправить сообщение на сервер!
2022-01-21 19:14:00,501 ERROR    client.py Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2022-01-21 19:15:24,563 ERROR    client.py Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2022-01-21 19:15:24,563 ERROR    client.py Не удалось отправить сообщение на сервер!
2022-01-21 19:15:24,564 ERROR    client.py Запрос на отправку или получение данных  (when sending on a datagram socket using a sendto call) no address was supplied
2022-01-21 19:15:25,564 ERROR    client.py Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2022-01-21 19:15:25,564 ERROR    client.py Не удалось отправить сообщение на сервер!
2022-01-21 19:15:25,564 ERROR    client.py Запрос на отправку или получение данных  (when sending on a datagram socket using a sendto call) no address was supplied
2022-01-21 19:15:26,565 ERROR    client.py Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2022-01-21 19:15:26,565 ERROR    client.py Попытка отправить не JSON
2022-01-21 19:15:26,565 ERROR    client.py Запрос на отправку или получение данных  (when sending on a datagram socket using a sendto call) no address was supplied
2022-01-21 19:15:36,230 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 19:15:36,231 DEBUG    client.py Отправлено сообщение на сервер: {"action": "error", "time": 1642781736.220143, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 19:15:36,231 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 19:15:36,231 DEBUG    client.py Отправлено сообщение на сервер: {"action": "presence", "time": 1642781736.220143, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 19:15:36,232 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 19:15:36,232 ERROR    client.py Попытка отправить не JSON
2022-01-21 19:22:43,931 ERROR    client.py Запрос на отправку или получение данных  (when sending on a datagram socket using a sendto call) no address was supplied
2022-01-21 19:30:18,943 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 19:30:18,943 DEBUG    client.py Отправлено сообщение на сервер: {"action": "error", "time": 1642782618.931345, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 19:30:18,944 DEBUG    client.py Получено сообщение с сервера: {'response': 400, 'error': 'Wrong action, try again'}
2022-01-21 19:30:18,944 INFO     client.py Клиент разорвал подключение с сервером
2022-01-21 19:30:18,944 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 19:30:18,945 DEBUG    client.py Отправлено сообщение на сервер: {"action": "presence", "time": 1642782618.931345, "type": "status", "user": {"account_name": "Client", "status": "Hello!"}}
2022-01-21 19:30:18,945 DEBUG    client.py Получено сообщение с сервера: {'response': 200, 'msg': 'Hi Client'}
2022-01-21 19:30:18,945 INFO     client.py Клиент разорвал подключение с сервером
2022-01-21 19:30:18,945 INFO     client.py Запущен клиент с параметрами адресс: 127.0.0.1, порт: 7777
2022-01-21 19:30:18,946 ERROR    client.py Попытка отправить не JSON
